/* LP RECIPE LIBRARY
   White-label recipes Jayme licensed to brand and use with his clients (Exceed OS Menopause Cookbook
   + Meal Plan Desk, 2026-09-16). The recipes stay as written. The engine only changes PORTIONS to fit
   a member's numbers, and swaps an ingredient only when her eating style or allergies require it.

   Row: {id, name, slot:'am'|'pm'|'snack', m:[kcal, protein, carbs, fat] PER SERVING (from the recipe),
         lead: the main protein (for her food picks), sides: foods that can be added to reach calories,
         how: a short method, ing:[[qty, unit, name, tags, section]] PER SERVING}
   tags: M meat, P pork, R red meat, F fish, S shellfish, E egg, D dairy, N tree nut, K peanut, G gluten, Y soy
   section: mf meat and fish, pp plant protein, ed eggs and dairy, pw protein powder, cg carbs and grains,
            fr fruit, vg vegetables, fx fats nuts and extras, ps pantry and spices
   Seasonings (ps) do not scale past a sensible amount. */
var RECIPE_LIBRARY=[
  /* ---------- breakfast ---------- */
  {id:'yogurt-bowl', name:'Creamy Vanilla Protein Yogurt Bowl', slot:'am', m:[236,25,25,4], lead:'nonfat Greek yogurt', sides:['berries','banana'],
   how:'Stir the protein powder, vanilla and maple syrup into the yogurt until smooth. Top with the fruit and hemp seeds.',
   ing:[[4.4,'oz','nonfat Greek yogurt','D','ed'],[0.5,'scoop','vanilla protein powder','D','pw'],[1,'tsp','vanilla extract','','ps'],[0.5,'tsp','maple syrup','','ps'],
        [1,'tbsp','blueberries','','fr'],[0.5,'','banana','','fr'],[1,'tsp','hemp seeds','','fx']]},
  {id:'strawberry-oats', name:'Strawberry Overnight Oats', slot:'am', m:[396,31,50,8], lead:'plant protein powder', sides:['berries','banana'],
   how:'Mix everything in a jar, cover and refrigerate for at least 2 hours or overnight. Keeps 5 days in the fridge.',
   ing:[[1.4,'oz','rolled oats','G','cg'],[0.5,'cup','unsweetened almond milk','N','ed'],[5,'oz','soy yogurt','Y','ed'],[1,'tbsp','chia seeds','','fx'],
        [1,'tbsp','maple syrup','','ps'],[1.3,'oz','strawberries','','fr'],[1,'scoop','vegan vanilla protein powder','','pw'],[0.5,'tsp','vanilla extract','','ps']]},
  {id:'blueberry-pancakes', name:'Blueberry Protein Pancakes', slot:'am', m:[238,36,19,2], lead:'egg whites', sides:['berries','banana'],
   how:'Whisk the egg whites and protein powder, fold in the mashed banana and blueberries (a splash of almond milk if thick). Cook in a lightly oiled pan over medium-low, about 5 minutes, flip, 2 to 3 more.',
   ing:[[4,'','egg whites','E','ed'],[1,'scoop','vanilla protein powder','D','pw'],[0.5,'','banana','','fr'],[4,'tbsp','blueberries','','fr'],[0.5,'tsp','coconut oil','','fx']]},
  {id:'zucchini-omelet', name:'Zucchini Parmesan Omelet', slot:'am', m:[298,33,10,14], lead:'egg whites', sides:['sourdough','berries','potatoes'],
   how:'Soften the onion in the oil, add the zucchini and cook 3 to 4 minutes. Whisk the egg, egg whites and Parmesan, pour over, cover and cook about 5 minutes until set.',
   ing:[[1,'tsp','olive oil','','fx'],[0.25,'','red onion','','vg'],[1,'','zucchini','','vg'],[1,'','whole eggs','E','ed'],[6.3,'oz','liquid egg whites','E','ed'],[2,'tbsp','grated Parmesan','D','ed']]},
  {id:'mousse-bowl', name:'Berry Protein Mousse Bowl', slot:'am', m:[173,24,17,1], lead:'whey protein powder', sides:['banana','sourdough','berries'],
   how:'Blend the frozen berries, protein powder and almond milk until smooth, then whip 5 to 8 minutes until fluffy.',
   ing:[[5.3,'oz','frozen berries','','fr'],[1,'scoop','vanilla protein powder','D','pw'],[0.25,'cup','unsweetened almond milk','N','ed']]},
  {id:'coffee-smoothie', name:'Iced Coffee Protein Smoothie', slot:'am', m:[242,25,31,2], lead:'whey protein powder', sides:['banana','sourdough'],
   how:'Blend the banana, protein powder, almond milk and cooled coffee. Add ice and maple syrup and blend again.',
   ing:[[0.5,'','banana','','fr'],[1,'scoop','vanilla protein powder','D','pw'],[0.5,'cup','unsweetened almond milk','N','ed'],[0.5,'cup','brewed coffee, cooled','','ps'],[1,'tsp','maple syrup','','ps']]},
  {id:'egg-muffins', name:'Cheesy Egg and Veggie Muffins', slot:'am', m:[210,23,6,10], lead:'egg whites', sides:['sourdough','berries','potatoes'],
   how:'Crisp the turkey bacon, soften the shallot, onion, pepper and broccoli. Whisk the egg whites and cottage cheese, add everything, fill a muffin tin, top with cheddar and bake at 350°F for 20 to 25 minutes (160°F inside). Make a batch.',
   ing:[[3,'slice','turkey bacon','M','mf'],[0.5,'tsp','olive oil','','fx'],[0.25,'','shallot','','vg'],[1,'','green onion','','vg'],[0.25,'','red bell pepper','','vg'],
        [0.5,'oz','broccoli','','vg'],[4,'oz','liquid egg whites','E','ed'],[1.3,'oz','cottage cheese','D','ed'],[1,'tbsp','shredded cheddar','D','ed']]},
  {id:'banana-pancakes', name:'Banana and Chocolate Protein Pancakes', slot:'am', m:[583,47,73,11], lead:'egg whites', sides:['berries'],
   how:'Blend the egg whites, egg, oats, protein powder, one banana and a splash of almond milk. Cook in coconut oil over medium, flip once. Top with the second banana and the maple syrup.',
   ing:[[4.2,'oz','liquid egg whites','E','ed'],[1,'','whole eggs','E','ed'],[1,'tbsp','unsweetened almond milk','N','ed'],[4,'tbsp','rolled oats','G','cg'],
        [1,'scoop','chocolate protein powder','D','pw'],[2,'','banana','','fr'],[1,'tbsp','maple syrup','','ps'],[1,'tsp','coconut oil','','fx']]},
  {id:'cappuccino-oats', name:'Protein Cappuccino Overnight Oats', slot:'am', m:[476,34,44,18], lead:'whey protein powder', sides:['berries','banana'],
   how:'Stir the protein powder into the almond milk, mix in the oats, almond butter and chia. Refrigerate overnight and top with kiwi and cacao nibs.',
   ing:[[1,'scoop','cappuccino protein powder','D','pw'],[0.75,'cup','unsweetened almond milk','N','ed'],[1.4,'oz','rolled oats','G','cg'],[1,'tbsp','almond butter','N','fx'],
        [2,'tsp','chia seeds','','fx'],[1,'','kiwi','','fr'],[0.5,'tsp','cacao nibs','','ps']]},
  {id:'turkey-patties', name:'Turkey Sausage Breakfast Patties', slot:'am', m:[254,28,3,14], lead:'93% ground turkey', sides:['potatoes','sourdough','berries'],
   how:'Soften the onion and garlic with the fennel seeds, cool, then mix into the turkey with the vinegar, chives and spices. Shape into patties and pan-cook 4 to 5 minutes a side (165°F inside). Make a batch.',
   ing:[[0.33,'tsp','olive oil','','fx'],[0.33,'','small onion','','vg'],[0.33,'clove','garlic','','vg'],[0.33,'tsp','fennel seeds','','ps'],[5.3,'oz','lean ground turkey','M','mf'],
        [1,'tsp','red wine vinegar','','ps'],[1,'tsp','chives','','vg'],[0.25,'tsp','paprika','','ps']]},
  {id:'egg-avo-bowl', name:'Egg, Bacon and Avocado Breakfast Bowl', slot:'am', m:[373,27,8,26], lead:'whole eggs', sides:['sourdough','potatoes','berries'],
   how:'Hard-boil the eggs and cook the bacon. Chop both with the avocado and top with the red onion and pepper.',
   ing:[[2,'slice','bacon medallions','M P','mf'],[2,'','whole eggs','E','ed'],[0.5,'','avocado','','fx'],[1,'tbsp','red onion','','vg'],[1,'tbsp','red bell pepper','','vg']]},
  {id:'shrimp-skillet', name:'Shrimp and Sunny Egg Power Skillet', slot:'am', m:[281,29,4,17], lead:'shrimp', sides:['sourdough','potatoes'],
   how:'Soften the onion in the oil, add the tomatoes, spinach and shrimp until pink (145°F). Make wells, crack in the eggs, cover and cook until set. Finish with parsley and cayenne.',
   ing:[[0.5,'tsp','olive oil','','fx'],[0.13,'','onion','','vg'],[2,'','cherry tomatoes','','vg'],[0.5,'handful','spinach','','vg'],[5,'','shrimp','S','mf'],[3,'','whole eggs','E','ed'],[0.25,'tsp','cayenne','','ps']]},
  {id:'cottage-waffles', name:'Oatmeal Cottage Cheese Waffles', slot:'am', m:[309,23,21,15], lead:'low-fat cottage cheese', sides:['berries','banana'],
   how:'Blend the eggs, cottage cheese, oats and baking powder until smooth. Cook in an oiled waffle iron until golden. They freeze well.',
   ing:[[1,'','whole eggs','E','ed'],[4,'oz','cottage cheese','D','ed'],[1,'oz','rolled oats','G','cg'],[0.25,'tsp','baking powder','','ps'],[0.25,'tsp','olive oil','','fx']]},

  /* ---------- lunch and dinner ---------- */
  {id:'salmon-nicoise', name:'Easy Salmon Nicoise Salad', slot:'pm', m:[338,40,13,14], lead:'salmon', sides:['potatoes','sourdough','quinoa'],
   how:'Steam the salmon 10 minutes (145°F), boil the green beans 6 minutes and the eggs 5 to 6. Blend the olives, mix half with the yogurt and vinegar, toss with the beans, and top with the salmon, eggs and the rest of the olive paste.',
   ing:[[4.5,'oz','salmon fillet','F','mf'],[5.3,'oz','green beans','','vg'],[1,'','whole eggs','E','ed'],[5,'','black olives','','fx'],[1,'tbsp','nonfat Greek yogurt','D','ed'],[0.5,'tbsp','apple cider vinegar','','ps']]},
  {id:'coronation-chicken', name:'Coronation Chicken Salad', slot:'pm', m:[228,25,14,8], lead:'chicken breast', sides:['sourdough','brown rice','quinoa'],
   how:'Mix the mayo, yogurt and curry powder, then stir in the cooked chicken, apricots and celery. Serve on greens or in a sandwich.',
   ing:[[0.5,'tbsp','mayonnaise','E','fx'],[1,'tbsp','nonfat Greek yogurt','D','ed'],[0.5,'tsp','curry powder','','ps'],[2.5,'oz','cooked chicken breast','M','mf'],[0.7,'oz','dried apricots','','fr'],[0.5,'','celery stick','','vg']]},
  {id:'blt-chicken', name:'BLT Chicken Salad', slot:'pm', m:[385,44,5,21], lead:'chicken breast', sides:['sourdough','potatoes','quinoa'],
   how:'Massage the kale with the oil. Toss with the shredded chicken, bacon, tomatoes and onion, then stir in a sauce of yogurt, ranch seasoning, lemon and hot sauce.',
   ing:[[0.6,'oz','kale','','vg'],[0.25,'tsp','olive oil','','fx'],[4,'oz','cooked chicken breast','M','mf'],[1.5,'slice','bacon','M P','mf'],[1.3,'oz','cherry tomatoes','','vg'],
        [0.13,'','red onion','','vg'],[1.25,'oz','nonfat Greek yogurt','D','ed'],[0.25,'tsp','ranch seasoning','','ps'],[0.5,'tsp','lemon juice','','ps']]},
  {id:'tuna-quinoa', name:'Tuna and Quinoa Salad Bowl', slot:'pm', m:[359,32,33,11], lead:'canned tuna', sides:['quinoa','sourdough'],
   how:'Whisk the oil, vinegar, lemon and Dijon. Toss with the quinoa, chickpeas, cucumber, tomatoes, feta and tuna.',
   ing:[[3.25,'oz','cooked quinoa','','cg'],[2,'tbsp','chickpeas','','pp'],[0.25,'','cucumber','','vg'],[0.5,'tbsp','crumbled feta','D','ed'],[5,'','cherry tomatoes','','vg'],
        [1,'','can tuna in water','F','mf'],[0.5,'tbsp','olive oil','','fx'],[1,'tsp','red wine vinegar','','ps'],[0.5,'tsp','Dijon mustard','','ps']]},
  {id:'southwest-chicken', name:'Quick Southwest Chicken Salad', slot:'pm', m:[321,43,26,5], lead:'chicken breast', sides:['brown rice','white rice','sweet potato'],
   how:'Mix the yogurt, lime, cumin, chili powder, salt and sriracha, then fold in the chicken, corn, black beans, onion, cilantro and pepper.',
   ing:[[4,'oz','cooked chicken breast','M','mf'],[1.3,'oz','sweet corn','','cg'],[1.5,'oz','black beans','','pp'],[0.25,'','small red onion','','vg'],[1,'tbsp','cilantro','','vg'],
        [0.25,'','red bell pepper','','vg'],[1,'oz','nonfat Greek yogurt','D','ed'],[0.25,'','lime','','fr'],[0.25,'tsp','cumin','','ps'],[0.5,'tsp','sriracha','','ps']]},
  {id:'greek-tofu', name:'Greek Tofu Bowl', slot:'pm', m:[275,29,24,7], lead:'extra-firm tofu', sides:['quinoa','brown rice','sourdough'],
   how:'Crumble the tofu into a little hot oil, add the Greek seasoning, onion, pepper, olives, sun-dried tomatoes, parsley and lemon, and cook 3 minutes. Serve over the greens.',
   ing:[[7,'oz','extra-firm tofu','Y','pp'],[0.25,'','small onion','','vg'],[0.25,'','red bell pepper','','vg'],[2.5,'','sun-dried tomatoes','','vg'],[3,'','kalamata olives','','fx'],
        [0.75,'tbsp','Greek seasoning','','ps'],[0.25,'','lemon','','fr'],[1,'oz','mixed greens','','vg']]},
  {id:'feta-chicken', name:'Spinach and Feta Stuffed Chicken', slot:'pm', m:[278,43,4,10], lead:'chicken breast', sides:['potatoes','brown rice','sweet potato','quinoa'],
   how:'Cut a pocket in the chicken, rub with the spices, and stuff with the spinach, feta, ricotta, green onion, garlic and dill. Sear in the oil 3 to 4 minutes a side, then bake at 400°F about 20 minutes (165°F inside).',
   ing:[[6,'oz','chicken breast (raw)','M','mf'],[0.5,'tsp','paprika','','ps'],[0.25,'tsp','oregano','','ps'],[0.5,'tbsp','olive oil','','fx'],[1.25,'oz','frozen spinach','','vg'],
        [0.6,'oz','feta','D','ed'],[1,'tbsp','ricotta','D','ed'],[0.5,'tbsp','green onion','','vg'],[0.5,'clove','garlic','','vg']]},
  {id:'lemon-salmon', name:'Herby Lemon Salmon with Greek Salad', slot:'pm', m:[379,42,10,19], lead:'salmon', sides:['potatoes','quinoa','sourdough','brown rice'],
   how:'Toss the salmon with a little oil, lemon, garlic, oregano and dill, rest 15 minutes, and air-fry at 400°F for 7 to 9 minutes (145°F). Toss the tomatoes, cucumber, onion, olives, parsley and feta with oil and red wine vinegar.',
   ing:[[6,'oz','salmon fillet','F','mf'],[1,'tbsp','olive oil','','fx'],[0.25,'','lemon','','fr'],[0.75,'','tomato','','vg'],[0.25,'','cucumber','','vg'],
        [0.13,'','red onion','','vg'],[1.25,'oz','kalamata olives','','fx'],[0.5,'oz','feta','D','ed'],[0.5,'tbsp','red wine vinegar','','ps']]},
  {id:'chicken-caprese', name:'Chicken Caprese with Balsamic Tomato Salad', slot:'pm', m:[296,34,4,16], lead:'chicken breast', sides:['whole-wheat pasta','potatoes','sourdough','quinoa'],
   how:'Season the chicken with garlic powder, lemon zest and oregano. Sear 5 minutes, turn, cook 5 to 6 more (165°F), top with mozzarella and cover to melt. Toss the tomatoes with basil, oil and balsamic.',
   ing:[[4,'oz','chicken breast (raw)','M','mf'],[1.5,'oz','fresh mozzarella','D','ed'],[2.6,'oz','cherry tomatoes','','vg'],[4,'','basil leaves','','vg'],[0.25,'tbsp','olive oil','','fx'],[1,'tsp','balsamic glaze','','ps']]},
  {id:'broccoli-alfredo', name:'Chicken Broccoli Alfredo', slot:'pm', m:[488,40,55,12], lead:'chicken breast', sides:['whole-wheat pasta'],
   how:'Cook the pasta and add the broccoli for the last 3 to 4 minutes. Cook the seasoned chicken in half the butter (165°F). Melt the rest with the garlic, stir in the flour, whisk in the milk, simmer 2 to 3 minutes, add the Parmesan and toss it all together.',
   ing:[[2,'oz','rotini pasta (dry)','G','cg'],[2.6,'oz','broccoli','','vg'],[0.5,'tbsp','butter','D','fx'],[4,'oz','chicken breast (raw)','M','mf'],[0.5,'clove','garlic','','vg'],
        [0.5,'tbsp','flour','G','cg'],[0.33,'cup','milk','D','ed'],[1,'tbsp','grated Parmesan','D','ed']]},
  {id:'beef-leek-soup', name:'Creamy Beef and Leek Soup', slot:'pm', m:[355,25,12,23], lead:'93% ground beef', sides:['sourdough','potatoes'],
   how:'Brown the beef in the oil (160°F), add the leek, pour in the stock and simmer 5 minutes. Stir in the cream cheese and paprika and cook 5 more until thick.',
   ing:[[0.5,'tbsp','olive oil','','fx'],[3.5,'oz','lean ground beef','M R','mf'],[0.5,'','leek','','vg'],[1.4,'cup','vegetable stock','','ps'],[1.75,'oz','reduced-fat cream cheese','D','ed'],[0.25,'tsp','paprika','','ps']]},
  {id:'white-bean-tuna', name:'White Bean Tuna Salad', slot:'pm', m:[351,22,32,15], lead:'canned tuna', sides:['sourdough'],
   how:'Toss the onion, parsley, cannellini beans, tuna and tomatoes with the oil and white wine vinegar. Season and chill.',
   ing:[[0.25,'','red onion','','vg'],[1,'tbsp','parsley','','vg'],[5.3,'oz','cannellini beans','','pp'],[2.1,'oz','canned tuna','F','mf'],[3.5,'oz','cherry tomatoes','','vg'],[1,'tbsp','olive oil','','fx'],[1,'tbsp','white wine vinegar','','ps']]},
  {id:'cod-curry', name:'Cod and Vegetable Curry', slot:'pm', m:[352,29,14,20], lead:'white fish (cod or tilapia)', sides:['white rice','brown rice'],
   how:'Soften the onion, stir in the curry paste for a minute, add the coconut milk and bring to a boil. Add the fish and frozen vegetables and simmer 15 minutes (145°F).',
   ing:[[0.25,'','onion','','vg'],[0.75,'tbsp','green curry paste','S','ps'],[0.33,'cup','coconut milk','','fx'],[5.3,'oz','white fish fillet','F','mf'],[3.2,'oz','frozen mixed vegetables','','vg']]},
  {id:'prosciutto-chicken', name:'Prosciutto Wrapped Chicken with Lentils', slot:'pm', m:[474,46,42,14], lead:'chicken thighs', sides:['sourdough'],
   how:'Cut the thigh in two, season, spread with red pesto and wrap in prosciutto. Bake at 360°F for 25 to 30 minutes (165°F). Warm the lentils with the sun-dried tomatoes and a splash of cider vinegar.',
   ing:[[1,'','chicken thigh','M','mf'],[2,'slice','prosciutto','M P','mf'],[2,'tsp','red pesto','D N','fx'],[7,'oz','canned lentils','','pp'],[1.25,'oz','sun-dried tomatoes','','vg']]},
  {id:'turkey-meatballs', name:'Turkey Meatballs with Couscous Salad', slot:'pm', m:[488,41,54,12], lead:'93% ground turkey', sides:['quinoa'],
   how:'Mix the turkey with softened onion, garlic, half the mint and lemon zest, roll into balls and brown 10 minutes, then cover 5 (165°F). Soak the couscous in hot stock 15 minutes and stir in peas, radishes and lemon. Serve with a yogurt, garlic and mint sauce.',
   ing:[[0.5,'tbsp','coconut oil','','fx'],[0.25,'','onion','','vg'],[4,'oz','ground turkey','M','mf'],[1,'tbsp','mint','','vg'],[0.25,'','lemon','','fr'],
        [1.75,'oz','nonfat Greek yogurt','D','ed'],[1.75,'oz','couscous (dry)','G','cg'],[1.75,'oz','frozen peas','','vg'],[2,'','radishes','','vg']]},
  {id:'cajun-salmon', name:'Spiced Cajun Salmon with Corn Salsa Salad', slot:'pm', m:[425,38,15,24], lead:'salmon', sides:['brown rice','white rice','potatoes','sweet potato'],
   how:'Rub the salmon with Cajun seasoning and bake or air-fry until 145°F. Char the corn, cut it off the cob and toss with the tomatoes and coriander.',
   ing:[[1,'','salmon fillet','F','mf'],[0.5,'','corn cob','','cg'],[2.6,'oz','cherry tomatoes','','vg'],[0.5,'oz','coriander','','vg'],[0.5,'tbsp','Cajun seasoning','','ps']]},
  {id:'lemon-chicken', name:'One Pot Lemon Chicken with Capers', slot:'pm', m:[327,26,3,23], lead:'chicken breast', sides:['potatoes','brown rice','whole-wheat pasta'],
   how:'Brown the chicken in the butter, add the capers and lemon juice and simmer until cooked through (165°F). Finish with parsley.',
   ing:[[4,'oz','chicken breast (raw)','M','mf'],[1.75,'tbsp','butter','D','fx'],[1,'tbsp','capers','','ps'],[0.75,'','lemon','','fr'],[1,'tbsp','parsley','','vg']]},
  {id:'mexican-peppers', name:'Easy Stuffed Mexican Peppers', slot:'pm', m:[274,23,18,12], lead:'93% ground beef', sides:['brown rice','white rice','black beans'],
   how:'Brown the beef (160°F) with the Mexican spices, stir in the tomatoes and cooked rice, fill the halved peppers and bake at 375°F for 25 to 30 minutes.',
   ing:[[1,'','bell pepper','','vg'],[3.5,'oz','lean ground beef','M R','mf'],[3.5,'oz','canned chopped tomatoes','','vg'],[1.4,'oz','cooked rice','','cg'],[0.5,'tbsp','Mexican spice blend','','ps']]},

  /* ---------- snacks and protein boosters ---------- */
  {id:'tuna-dip', name:'Tuna and White Bean Protein Dip', slot:'snack', m:[145,23,11,1], lead:'canned tuna',
   how:'Mash the beans, then mix in the tuna, yogurt, lemon, garlic and parsley. Eat with raw veggies.',
   ing:[[2.5,'oz','canned tuna','F','mf'],[2,'oz','white beans','','pp'],[1,'tbsp','nonfat Greek yogurt','D','ed'],[0.5,'tbsp','lemon juice','','ps']]},
  {id:'cottage-ice-cream', name:'Blueberry Cottage Cheese Ice Cream', slot:'snack', m:[252,28,26,4], lead:'low-fat cottage cheese',
   how:'Blend the cottage cheese, banana and protein powder, stir in the dried blueberries and freeze 90 minutes, stirring halfway.',
   ing:[[0.5,'cup','cottage cheese','D','ed'],[0.5,'','banana','','fr'],[0.5,'scoop','vanilla protein powder','D','pw'],[2,'tbsp','dried blueberries','','fr']]},
  {id:'pb-berry-shake', name:'PB and Berry Power Shake', slot:'snack', m:[258,27,15,10], lead:'whey protein powder',
   how:'Blend the almond milk, frozen strawberries, protein powder and peanut butter until smooth.',
   ing:[[0.5,'cup','unsweetened almond milk','N','ed'],[3.9,'oz','frozen strawberries','','fr'],[1,'scoop','vanilla protein powder','D','pw'],[1,'tbsp','peanut butter','K','fx']]},
  {id:'cinnamon-shake', name:'Cinnamon Roll Protein Shake', slot:'snack', m:[178,24,16,2], lead:'whey protein powder',
   how:'Blend the banana, protein powder, cinnamon and almond milk with ice.',
   ing:[[0.5,'','banana','','fr'],[1,'scoop','vanilla protein powder','D','pw'],[0.5,'tsp','cinnamon','','ps'],[0.5,'cup','unsweetened almond milk','N','ed']]},
  {id:'yogurt-fluff', name:'Yogurt and Peanut Butter Protein Fluff', slot:'snack', m:[219,16,14,11], lead:'nonfat Greek yogurt',
   how:'Whisk the Greek yogurt, peanut butter and sweetener until fluffy.',
   ing:[[4.4,'oz','Greek yogurt','D','ed'],[1,'tbsp','peanut butter','K','fx'],[1,'tsp','stevia','','ps']]}
];

/* Swaps used ONLY when her eating style or allergies require them. Each keeps the recipe the same dish. */
var RECIPE_SWAPS=[
  {match:/whey protein powder|^vanilla protein powder|chocolate protein powder|cappuccino protein powder/, need:'D', to:'plant protein powder', tags:''},
  {match:/nonfat Greek yogurt|^Greek yogurt/, need:'D', to:'dairy-free Greek-style yogurt', tags:''},
  {match:/^milk$/, need:'D', to:'unsweetened oat milk', tags:''},
  {match:/^butter$/, need:'D', to:'olive oil', tags:''},
  {match:/grated Parmesan|shredded cheddar|feta|fresh mozzarella/, need:'D', to:'dairy-free cheese', tags:''},
  {match:/almond milk/, need:'N', to:'unsweetened oat milk', tags:''},
  {match:/almond butter/, need:'N', to:'sunflower seed butter', tags:''},
  {match:/peanut butter/, need:'K', to:'sunflower seed butter', tags:''},
  {match:/rolled oats/, need:'G', to:'certified gluten-free oats', tags:''},
  {match:/rotini pasta/, need:'G', to:'gluten-free pasta (dry)', tags:''},
  {match:/couscous/, need:'G', to:'quinoa (dry)', tags:''},
  {match:/^flour$/, need:'G', to:'gluten-free flour', tags:''},
  {match:/soy yogurt/, need:'Y', to:'coconut yogurt', tags:''},
  {match:/bacon medallions|^bacon$/, need:'P', to:'turkey bacon', tags:'M'},
  {match:/lean ground beef/, need:'R', to:'lean ground turkey', tags:'M'},
  {match:/green curry paste/, need:'S', to:'shrimp-free curry paste', tags:''}
];
